# Start of /etc/rad/config.toml (example)

[arch]
multilib = false

[build]
cores = 2
ask = true
bin_cache_dir = "~/.rad/bin"
allow_unfree = false

[repo]
url = "https://raw.githubusercontent.com/dejuri/radpkg/main/stable-13"
overlays = [
	"/home/adolf/.rad/overlay/radolf",
	"https://raw.githubusercontent.com/adolfisveryavgn/radpkg/main/unstable"
]

# End
